# Generated by Django 6.0.3 on 2026-03-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
