# Generated by Django 6.0.3 on 2026-03-09 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingspace_lat_alter_parkingspace_lon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'ממתין לאישור'), ('approved', 'מאושר'), ('canceled', 'בוטל'), ('completed', 'הסתיים')], default='pending', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingspace')),
            ],
        ),
    ]
