# Generated by Django 6.0.3 on 2026-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='instructions',
            field=models.TextField(blank=True, help_text="הוראות מיוחדות למשתמשים (למשל: מיקום מדויק, דרכי גישה, וכו')", null=True),
        ),
    ]
