# Generated by Django 6.0.3 on 2026-03-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkingspace_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='available_fri',
            field=models.BooleanField(default=True, verbose_name="ו'"),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='available_mon',
            field=models.BooleanField(default=True, verbose_name="ב'"),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='available_sat',
            field=models.BooleanField(default=True, verbose_name="ש'"),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='available_sun',
            field=models.BooleanField(default=True, verbose_name="א'"),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='available_thu',
            field=models.BooleanField(default=True, verbose_name="ה'"),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='available_tue',
            field=models.BooleanField(default=True, verbose_name="ג'"),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='available_wed',
            field=models.BooleanField(default=True, verbose_name="ד'"),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='end_date',
            field=models.DateField(blank=True, help_text='תאריך סיום לזמינות החניה', null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='start_date',
            field=models.DateField(blank=True, help_text='תאריך התחלה לזמינות החניה', null=True),
        ),
    ]
