# Generated by Django 6.0.3 on 2026-03-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingspace_available_fri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='available_from',
            field=models.TimeField(blank=True, help_text='שעת התחלה לזמינות החניה בכל יום', null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='available_to',
            field=models.TimeField(blank=True, help_text='שעת סיום לזמינות החניה בכל יום', null=True),
        ),
    ]
