# Generated by Django 6.0.3 on 2026-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parkingspace_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין לאישור'), ('approved', 'מאושר'), ('cancelled', 'בוטל'), ('completed', 'הסתיים')], default='pending', max_length=20),
        ),
    ]
