# Generated by Django 6.0.3 on 2026-03-12 21:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_alter_booking_status_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
