# Generated by Django 6.0.3 on 2026-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_profile_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='legal_declaration',
            field=models.BooleanField(default=False),
        ),
    ]
