# Generated by Django 6.0.3 on 2026-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_parkingspace_legal_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='legal_declaration',
            field=models.BooleanField(default=False, help_text='חובה לאשר את ההצהרה המשפטית כדי להוסיף חניה למערכת.', verbose_name='אני מאשר שהחנייה בבעלותי או שיש לי אישור חוקי להשכיר אותה.'),
        ),
    ]
