# Generated by Django 6.0.3 on 2026-03-15 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_alter_parkingspace_legal_declaration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'חניה לא קיימת'), ('not_owner', 'החניה לא בבעלות המפרסם'), ('inaccurate_info', 'מידע לא מדויק'), ('scam', 'חשד להונאה'), ('other', 'אחר')], max_length=20)),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור נוסף (אופציונלי)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='טופל')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='parking.parkingspace')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
