# Generated by Django 6.0.3 on 2026-03-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rating_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('fake', 'חניה לא קיימת'), ('not_owner', 'החניה לא בבעלות המפרסם'), ('inaccurate_info', 'מידע לא מדויק'), ('scam', 'חשד להונאה'), ('other', 'אחר')], max_length=20, verbose_name='סיבת הדיווח'),
        ),
    ]
