# Generated by Django 6.0.3 on 2026-04-14 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_booking_rated_at_booking_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=100, verbose_name='כותרת')),
                ('message_content', models.TextField(verbose_name='תוכן ההודעה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('is_read', models.BooleanField(default=False, verbose_name='נקרא')),
                ('notification_type', models.CharField(choices=[('new_booking', 'הזמנה חדשה'), ('report', 'דיווח על חניה'), ('order_canceled', 'הזמנה בוטלה'), ('order_confirmed', 'הזמנה אושרה')], max_length=100, verbose_name='סוג התראה')),
                ('target_url', models.URLField(verbose_name='קישור ליעד')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='מקבל')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
