services:
  db:
    image: postgres:15-alpine
    container_name: parky-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parky-network

  redis:
    image: redis:7-alpine
    container_name: parky-redis
    restart: always
    networks:
      - parky-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parky-app
    restart: always
    command: daphne -b 0.0.0.0 -p 8000 parky_project.asgi:application
    volumes:
      - .:/parky
      - static_volume:/parky/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - parky-network

networks:
  parky-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume: